#!/bin/bash
# Enterprise Dashboard Preview Script
# Provides consolidated view of all key metrics

echo "=== ENTERPRISE DASHBOARD PREVIEW ==="
echo "Time: $(date '+%Y-%m-%d %H:%M:%S %Z')"
echo "Repository: Bot-MVP"
echo "URL: https://github.com/kamva-Jack-hub1/Bot-MVP"
echo "Chief of Staff: Jack 🦞"
echo ""

# Key metrics section
echo "📊 KEY ENTERPRISE METRICS:"
echo "1. Performance Dashboard: performance-dashboard/PERFORMANCE_DASHBOARD_WITH_TEAM_VISIBILITY.html"
echo "2. Live Tracking Database: performance-dashboard/team_work_tracking_database.json"
echo "3. Accountability Framework: accountability/CHIEF_OF_STAFF_ACCOUNTABILITY_FRAMEWORK.md"
echo "4. Bot Project Catch-up Plan: team-outputs/BOT_PROJECT_CATCH_UP_PLAN.md"
echo "5. Team Directories: team-outputs/{otis,mara,silas,cleo}/"
echo "6. Documentation: docs/ directory"
echo "7. Automation Scripts: scripts/ directory"
echo "8. Memory Systems: memory/ directory"
echo ""

# Git status section
echo "🔄 REPOSITORY STATUS:"
echo "Recent commits:"
git log --oneline -3 2>/dev/null || echo "  (git not available in current context)"
echo ""
echo "Uncommitted changes:"
git status --short 2>/dev/null || echo "  (git not available in current context)"
echo ""

# Team output section
echo "👥 TEAM OUTPUT STATUS:"
total_files=0
for agent in otis mara silas cleo; do
    if [ -d "team-outputs/$agent" ]; then
        count=$(find "team-outputs/$agent" -type f \( -name "*.md" -o -name "*.json" -o -name "*.py" -o -name "*.csv" -o -name "*.txt" \) 2>/dev/null | wc -l)
        echo "  $agent: $count files"
        total_files=$((total_files + count))
    else
        echo "  $agent: Directory not found"
    fi
done
echo "Total team files: $total_files"
echo ""

# Quick previews section
echo "📄 DOCUMENT PREVIEWS (first 2 lines each):"
echo ""
echo "🔹 ACCOUNTABILITY FRAMEWORK:"
head -2 accountability/CHIEF_OF_STAFF_ACCOUNTABILITY_FRAMEWORK.md 2>/dev/null || echo "  File not found"
echo ""
echo "🔹 BOT PROJECT CATCH-UP PLAN:"
head -2 team-outputs/BOT_PROJECT_CATCH_UP_PLAN.md 2>/dev/null || echo "  File not found"
echo ""
echo "🔹 PERFORMANCE DASHBOARD STATUS:"
if [ -f "performance-dashboard/team_work_tracking_database.json" ]; then
    echo "  Tracking database exists ($(wc -l < performance-dashboard/team_work_tracking_database.json) lines)"
else
    echo "  Tracking database not found"
fi
echo ""

# Next actions section
echo "🚀 NEXT ACTIONS:"
echo "1. Run: glow [file.md] for beautiful terminal previews"
echo "2. Run: grip README.md 8080 for web preview"
echo "3. Visit: https://github.com/kamva-Jack-hub1/Bot-MVP for web interface"
echo "4. Monitor: team-outputs/ directories for new work"
echo ""

echo "=== END ENTERPRISE DASHBOARD ==="
echo "Generated by Chief of Staff 🦞"
